### ISSUE TITLE
CodeSigning

### ISSUE THREAD

**Issue by BBBDC** [123FLO321/RealDeviceRaidMap#2]
In the Installation Guide you say: "Enter and choose your Signing Certificate for RDRaidMapCtrlUITests"

But the RDRaidMapCtrlUITests itself can't be signed, only the Project RDRaidMapCtrl as seen below. If that's not the case can you tell me where to sign the UITests

![screen shot 2018-05-16 at 17 52 26](https://user-images.githubusercontent.com/39342972/40128626-5db2ed64-5932-11e8-909c-7e651c952b81.png)

**Comment by BBBDC** [comment]
These are the error I get if I set up everything like above:

![screen shot 2018-05-16 at 17 58 29](https://user-images.githubusercontent.com/39342972/40128792-dd3086b4-5932-11e8-82ff-ad5e61bdc7d0.png)

**Comment by 123FLO321** [comment]
Try also setting the Development Team for the UI-Test not only the Main App.
